dotenv: .env

networks:
    default: development

    development:
      host: http://127.0.0.1
      gas_price: 0
      persist: false
      reverting_tx_gas_limit: 6721975
      test_rpc:
        fork: https://polygon-mainnet.g.alchemy.com/v2/iau-uzu7ghda0v8fr2g5p34
        cmd: ganache-cli
        port: 8545
        gas_limit: 6721975
        accounts: 11
        evm_version: istanbul
        mnemonic: mean ahead wire antique fiber detail clog mail anchor mail zone sign
      
    rinkeby:
      host: https://rinkeby.infura.io/v3/${INFURA_KEY}
      accounts: [RINKEBY_PRIVATE_KEY]
      gas_limit: 2000000
      gas_price: 20000000000

    polygon:
      host: https://polygon-mainnet.infura.io/v3/${INFURA_KEY}
      accounts: [MATIC_PRIVATE_KEY]
      gas_limit: 2000000
      gas_price: 20000000000



etherscan:
  apiKey: ETHERSCAN_API_KEY


compiler:
    solc:
      #version: 0.7.6
      version: 0.8.3
      remappings:
        - "@openzeppelin=./modules/OpenZeppelin/openzeppelin-contracts@4.0.0"
        - "@superfluid-finance/ethereum-contracts=./modules/superfluid-finance/ethereum-contracts"
        - "@uniswap/v2-periphery=./modules/Uniswap/v2-periphery@1.1.0-beta.0"
        - "@uniswap/v2-core=./modules/Uniswap/v2-core@1.0.1"