dotenv: .env

networks:
  default: development

  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 80000
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      port: 8545
      gas_limit: 6721975
      accounts: 10
      fork: ${MAINNET_API_URL}
      host: https://127.0.0.1
      mnemonic: ${MNEMONIC}

etherscan:
  apiKey: ${ETHERSCAN_API_KEY}

compiler:
    solc:
      version: 0.8.3
      remappings:
        - "@openzeppelin=./modules/OpenZeppelin/openzeppelin-contracts"
        - "@superfluid-finance/ethereum-contracts=./modules/superfluid-finance/ethereum-contracts"
        - "@uniswap/v2-periphery=./modules/Uniswap/v2-periphery"
        - "@uniswap/v2-core=./modules/Uniswap/v2-core"
