dotenv: .env
autofetch_sources: true

compiler:
    solc:
      version: 0.8.3
      remappings:
        - "@openzeppelin=./modules/OpenZeppelin/openzeppelin-contracts"
        - "@superfluid-finance/ethereum-contracts=./modules/superfluid-finance/ethereum-contracts"
        - "@uniswap/v2-periphery=./modules/Uniswap/v2-periphery"
        - "@uniswap/v2-core=./modules/Uniswap/v2-core"
