dotenv: .env


networks:
  default: development

  rinkeby:
    host: https://rinkeby.infura.io/v3/${INFURA_KEY}
    accounts: [MATIC_PRIVATE_KEY]
    gas_limit: 2000000
    gas_price: 20000000000

  polygon:
    host: https://polygon-mainnet.infura.io/v3/${INFURA_KEY}
    accounts: [MATIC_PRIVATE_KEY]
    gas_limit: 2000000
    gas_price: 20000000000

  
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      port: 8545
      gas_limit: 6721975
      accounts: 10
      chain_id: 1337
      network_id: 1588949648
      evm_version: istanbul
      fork: https://mainnet.infura.io/v3/29b8e685756646c8a1aa06c3f752e26b
      mnemonic: MNEMONIC
      block_time: 0
      default_balance: 100
      unlock: null
    
    
    
etherscan:
  apiKey: POLYSCAN_API_KEY

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.0.0
    - OpenZeppelin/openzeppelin-test-helpers@0.5.13
    - superfluid-finance/protocol-monorepo@0.1.2
    - Uniswap/v2-periphery@1.1.0-beta.0
    - Uniswap/v2-core@1.0.1

compiler:
    solc:
      version: 0.8.3
      remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
        - "@openzeppelin/test-helpers=OpenZeppelin/openzeppelin-test-helpers@0.5.13"
        - "@superfluid-finance/ethereum-contracts=superfluid-finance/protocol-monorepo@0.1.2/packages/ethereum-contracts"
        - "@uniswap/v2-periphery=Uniswap/v2-periphery@1.1.0-beta.0"
        - "@uniswap/v2-core=Uniswap/v2-core@1.0.1"
        
