live:
  - name: Polygon
    networks:
      - name: Mainnet (Alchemy)
        chainid: 137
        id: polygon-main-alchemy
        host: https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_POLYGON_KEY}
        explorer: https://api.polygonscan.com/api
        multicall2: "0xc8E51042792d7405184DfCa245F2d27B94D013b6"

development:
  - name: Ganache-CLI (Polygon-Mainnet Fork with Alchemy)
    id: polygon-main-alchemy-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: "pattern lumber mystery retreat answer wheel seminar adult practice air bring essence"
      fork: polygon-main-alchemy
