substitutions:
  _CHART_NAME: ricochet
  _NAMESPACE: ricochet
  _PROJECT_ID: block-sec # TODO: MXNC
  _TARGET_ZONE: us-central1-c
  _TARGET_CLUSTER: sandbox

steps:
# Build and Deploy React app in 02-Dapp
- name: 'gcr.io/cloud-builders/yarn'
  args: ['--cwd', './02-DApp']
  id: app-install
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['--cwd', './02-DApp', 'build']
  id: app-build
  waitFor: ['app-install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/ricochet:$COMMIT_SHA', './02-DApp']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/ricochet:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/ricochet:$COMMIT_SHA']

- name: 'gcr.io/$PROJECT_ID/helm'
  args: [
    'upgrade',
    '--install',
    '$_CHART_NAME',
    '--set', 'ricochet.image.repository=us.gcr.io/$PROJECT_ID/ricochet',
    '--set', 'ricochet.image.tag=$COMMIT_SHA',
    '--force',
    '--namespace',
    '$_NAMESPACE',
    './02-DApp/infrastructure'
  ]
  env:
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=$_NAMESPACE'
  - 'CLOUDSDK_COMPUTE_ZONE=$_TARGET_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_TARGET_CLUSTER'
