kind: Deployment
apiVersion: apps/v1
metadata:
  name: ricochet-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ricochet-react
  template:
    metadata:
      labels:
        app: ricochet-react
    spec:
      containers:
        - name: ricochet-react
          image: {{ .Values.ricochet.image.repository }}:{{ .Values.ricochet.image.tag }}
          imagePullPolicy: Always
          env:
            - name: REACT_APP_INFURA_TOKEN
              value: f046c2bf6d71458dab65361f31d41c6d
          ports:
            - containerPort: 80
      restartPolicy: Always
